vim.api.nvim_create_user_command("Recolor", function()
	vim.cmd("highlight Normal guibg=none")
	vim.cmd("highlight NormalNC guibg=none")
	vim.cmd("highlight NormalFloat guibg=none")
	vim.cmd("highlight Float guibg=none")
	vim.cmd("highlight FloatBackground guibg=none")
	vim.cmd("highlight FloatBorder guibg=none")
	vim.cmd("highlight FloatShadow guibg=none")
	vim.cmd("highlight Pmenu guibg=none")
	vim.cmd("highlight PmenuSel guibg=none")
	vim.cmd("highlight PmenuThumb guibg=none")
	vim.cmd("highlight PmenuBar guibg=none")
	vim.cmd("highlight PmenuExtra guibg=none")
	vim.cmd("highlight PmenuKind guibg=none")
	vim.cmd("highlight PmenuSbar guibg=none")
	vim.cmd("highlight PmenuExtraSel guibg=none")
	vim.cmd("highlight PmenuKindSel guibg=none")
end, {})

vim.cmd("Recolor")
